# Generated by Django 5.2.5 on 2025-12-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='gender',
        ),
    ]
