# Generated by Django 5.2.5 on 2025-12-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_userregistration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='current_weight',
            field=models.FloatField(blank=True, help_text='Weight in KG', null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in CM', null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='unit_preference',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10),
        ),
    ]
