# Generated by Django 5.2.5 on 2025-12-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_userregistration_current_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Walking', 'Walking'), ('Running', 'Running'), ('Biking', 'Biking')], max_length=50)),
                ('source', models.CharField(choices=[('app', 'In-App Tracker'), ('3rd_party', '3rd Party Connector')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userregistration')),
            ],
        ),
    ]
