# Generated by Django 5.2.5 on 2025-12-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
        ('registration', '0003_userregistration_current_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(default='Workout', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('host', models.CharField(max_length=150)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('group_goal_total', models.IntegerField(default=100)),
                ('group_workouts_completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_workouts', models.IntegerField(default=0)),
                ('current_week_progress', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('last_log_date', models.DateField(blank=True, null=True)),
                ('last_proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('last_caption', models.TextField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='fitness_app.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.challengeparticipant')),
            ],
            options={
                'unique_together': {('participant', 'date')},
            },
        ),
    ]
